import type { Metadata } from "next";
import "./globals.css";
import { fonts } from "@/utils/fonts";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts}>
      <body className="p-12">
        <Header />
        {children}
      </body>
    </html>
  );
}
